openapi: '3.0.3'
info:
  title: Stat-Dice
  description: |-
    Приложения для подсчета очков в разных играх

  contact:
    email: boombacks2711@gmail.com
  version: 1.0.0

servers:
  - url: http://localhost/
tags:
  - name: user
    description: User Info
  - name: lobby
    description: Lobby Info
  - name: games
    description: Game Info

paths:
  /user:
    put:
      tags:
        - user
